version: '3.8'

services:
  backend:
    build: ./backend
    container_name: cerevi_backend
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=${REDIS_URL}
      - DATA_PATH=/app/data
      - DEBUG=${DEBUG}
    volumes:
      - ./backend:/app
      - ./data:/app/data:ro
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: cerevi_redis
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 2gb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data

volumes:
  redis_data:
