"""Tests for redesigned unified API (/metadata, /data/{data_id}).

These tests intentionally minimal; they ensure new endpoints respond and
basic schema expectations hold. Tile / mesh retrieval are attempted only if
underlying data files exist (skip otherwise).
"""

import sys, os, json, gzip
import pytest
from fastapi.testclient import TestClient

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from app.main import app  # noqa

client = TestClient(app)


def test_health():
    r = client.get('/health')
    assert r.status_code == 200
    data = r.json()
    assert data['status'] == 'healthy'


def test_metadata_specimens():
    r = client.get('/metadata', params={'type': 'specimens'})
    assert r.status_code == 200
    data = r.json()
    assert isinstance(data, dict)
    assert 'RM009' in data
    sa = data['RM009']
    assert 'image' in sa
    assert "VISoR" in sa['image']
    assert "RAS_coordinate" in sa['image']['VISoR']


def test_metadata_regions():
    r = client.get('/metadata', params={'type': 'regions', 'specimen': 'RM009'})
    if r.status_code == 404:
        pytest.skip('Regions file missing in test environment')
    assert r.status_code == 200
    data = r.json()
    assert 'regions' in data or 'hierarchy' in data or isinstance(data, dict)


@pytest.mark.parametrize('view_token', ['xz', 'yz', 'xy'])
def test_data_image_tile(view_token):
    # Attempt to fetch tile at origin for level 0 channel 0
    data_id = f'RM009:img{view_token}:0:0:0,0,0'
    r = client.get(f'/data/{data_id}')
    if r.status_code == 404:
        pytest.skip('Image .ims file not present')
    elif r.status_code == 400:
        # Could be unsupported view if data orientation missing; treat as skip
        pytest.skip('View unsupported in current test data')
    else:
        assert r.status_code == 200
        # JPEG content for image modalities
        assert r.headers['content-type'] in ('image/jpeg', 'image/jpg')


def test_data_mask_tile():
    data_id = 'RM009:mskxz:0:0:0,0,0'
    r = client.get(f'/data/{data_id}')
    if r.status_code in (400, 404):
        pytest.skip('Mask atlas file not present')
    else:
        assert r.status_code == 200
        assert r.headers['content-type'] == 'image/png'


def test_data_mesh():
    data_id = 'RM009:meh3d:::brain_shell'
    r = client.get(f'/data/{data_id}')
    if r.status_code == 404:
        pytest.skip('Mesh file not present')
    elif r.status_code == 400:
        pytest.skip('Mesh modality unsupported in environment')
    else:
        assert r.status_code == 200
        assert 'text/plain' in r.headers['content-type']

        # Verify the OBJ header: third line should indicate Meshlab generator
        # Be tolerant of comment prefixes (e.g. '# ') that commonly appear in .obj files
        text = r.text
        lines = text.splitlines()
        if len(lines) < 3:
            pytest.skip('Mesh response too short to verify header')
        # Strip common comment markers and whitespace before comparison
        third = lines[2].lstrip('# ').strip()
        assert third == 'OBJ File Generated by Meshlab'


def test_json_compression():
    # Request specimens JSON with gzip accept header and ensure server gzips JSON responses
    headers = {'Accept-Encoding': 'gzip'}
    r = client.get('/metadata', params={'type': 'specimens'}, headers=headers)
    if r.status_code == 404:
        pytest.skip('Specimens metadata missing in test environment')
    assert r.status_code == 200

    # Server should indicate gzip encoding when it compressed the response
    enc = r.headers.get('Content-Encoding', '')
    assert 'gzip' in enc.lower()

    body = r.content
    # If the TestClient auto-decompressed, content won't start with gzip magic.
    if body[:2] == b'\x1f\x8b':
        decompressed = gzip.decompress(body)
    else:
        # Already decompressed by client
        decompressed = body

    # Ensure decompressed bytes are valid JSON
    data = json.loads(decompressed)
    assert isinstance(data, dict)
